Repository Your-News-On-Time/YourNewsonTime, pull requests merged in 2024-12, with the labels that each got.

#21 Add coil dependency
  app/build.gradle.kts
  app/src/main/java/app/yournewsontime/screens/FeedScreen.kt
  app/src/main/java/app/yournewsontime/ui/components/Footer.kt
  app/src/main/java/app/yournewsontime/ui/view/main/ArticleItem.kt
  app/src/main/java/app/yournewsontime/viewModel/NewYorkTimesViewModel.kt
  gradle/libs.versions.toml
Labels: enhancement

#28 Add filter by categories
  app/src/main/java/app/yournewsontime/MainActivity.kt
  app/src/main/java/app/yournewsontime/data/repository/CategoryRepository.kt
  app/src/main/java/app/yournewsontime/navigation/AppNavigation.kt
  app/src/main/java/app/yournewsontime/screens/FeedScreen.kt
  app/src/main/java/app/yournewsontime/screens/ProfileScreen.kt
  app/src/main/java/app/yournewsontime/screens/SavedScreen.kt
  app/src/main/java/app/yournewsontime/ui/components/DrawerContent.kt
  app/src/main/java/app/yournewsontime/ui/components/Footer.kt
  app/src/main/res/drawable/account_icon.png
  app/src/main/res/drawable/account_icon.xml
  app/src/main/res/drawable/bookmark_icon.png
  app/src/main/res/drawable/bookmark_icon.xml
  app/src/main/res/drawable/calendar_icon.xml
  app/src/main/res/drawable/close_menu_icon.xml
  app/src/main/res/drawable/filled_account_icon.xml
  app/src/main/res/drawable/filled_bookmark_icon.xml
  app/src/main/res/drawable/menu_icon.png
  app/src/main/res/drawable/menu_icon.xml
  app/src/main/res/drawable/today_icon.png
  app/src/main/res/drawable/today_icon.xml
Labels: bug, enhancement, invalid

#30 Resolve the problem with the icon menu
  app/src/main/java/app/yournewsontime/screens/FeedScreen.kt
Labels: bug

#31 Hot fix filter by category
  app/src/main/java/app/yournewsontime/MainActivity.kt
  app/src/main/java/app/yournewsontime/navigation/AppNavigation.kt
  app/src/main/java/app/yournewsontime/screens/ArticleScreen.kt
  app/src/main/java/app/yournewsontime/screens/FeedScreen.kt
  app/src/main/java/app/yournewsontime/ui/components/ArticleCard.kt
  app/src/main/java/app/yournewsontime/ui/view/main/ArticleItem.kt
  app/src/main/java/app/yournewsontime/viewModel/NewYorkTimesViewModel.kt
  app/src/main/java/app/yournewsontime/viewModel/NewYorkTimesViewModelFactory.kt
  app/src/main/java/app/yournewsontime/viewmodel/GoogleLoginViewModel.kt
Labels: hotfix

#40 Add MIT License file to the repository
  LICENSE
Labels: documentation

#41 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#45 Create profile screen
  app/src/main/AndroidManifest.xml
  app/src/main/java/app/yournewsontime/navigation/AppNavigation.kt
  app/src/main/java/app/yournewsontime/navigation/AppScreens.kt
  app/src/main/java/app/yournewsontime/screens/ArticleScreen.kt
  app/src/main/java/app/yournewsontime/screens/ProfileEditScreen.kt
  app/src/main/java/app/yournewsontime/screens/ProfileScreen.kt
  app/src/main/java/app/yournewsontime/ui/components/Footer.kt
Labels: enhancement, view

#47 Fetching the category when the user change the preferences
  app/src/main/java/app/yournewsontime/data/repository/CategoryRepository.kt
  app/src/main/java/app/yournewsontime/screens/FeedScreen.kt
  app/src/main/java/app/yournewsontime/ui/components/DrawerContent.kt
Labels: enhancement

#48 Add Biometric security
  app/build.gradle.kts
  app/src/main/java/app/yournewsontime/MainActivity.kt
  app/src/main/java/app/yournewsontime/data/repository/AppPreferencesRepository.kt
  app/src/main/java/app/yournewsontime/screens/ProfileEditScreen.kt
  gradle/libs.versions.toml
Labels: enhancement

#53 Add contribute section at readmemd
  CONTRIBUTING.md
  README.md
Labels: documentation

#54 Refactor the web
  index.html
  web/css/style.css
  web/images/App Icon.png
  web/images/YourNewsOnTimeLogo.webp
  web/images/YourNewsOnTimeNews.webp
  web/images/iphonex.png
  web/images/iphonex.webp
  web/images/playicon.png
Labels: bug, refactor
